# Generated by Django 4.2.5 on 2023-10-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='Value',
        ),
    ]
