# Generated by Django 4.2.5 on 2023-10-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_review_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demolink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sourcecode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
